version: '3.9'
services:
  app:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3001:3001
      - 3002:3002
    volumes:
      - ./src:/app/src
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
  